### ISSUE TITLE
Hotkeys enabled while typing in text box

### ISSUE THREAD

**Issue by Isteufar** [GarwelGarwel/SignalDelay#7]
The hotkeys are still enable while typing in rename vessel textbox for probes. Output.log not generated for latest play.

**Comment by GarwelGarwel** [comment]
Unfortunately, it seems to be a common KSP issue. I'll look into it, but I'm not sure I can solve it.

**Comment by GarwelGarwel** [comment]
What you can do is disable the mod before typing (just click the button in AppLauncher or Toolbar), then re-enable it again.
